config/routes.rb
Rails.application.routes.draw do

    devise_for :users
	root to:'home#index'
	resources :works

	get "/search",      to:"works#search"
  

	resources :works do 
		resources :comments
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :works
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :work
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :work
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works
  has_many :feedbacks
end

app/models/work.rb
class Work < ApplicationRecord

    WillPaginate.per_page = 7

    def self.search(search)
    	where("name LIKE ?", "%#{search}%")
  	end

    
    belongs_to :user
    belongs_to :category
    has_many   :feedbacks, dependent: :destroy
    has_many   :comments, dependent: :destroy
    has_many_attached :attaches
    validates :name, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @work = Work.find(params[:work_id])
        @comment = @work.comments.create(params[:comment].permit(:rating,:body))
        redirect_to work_path(@work)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

	before_action :find_work,only:[:show,:destroy, :edit, :update]
	before_action :authenticate_user!

	def index
		if params[:category].blank?
		@works = Work.all.order("created_at DESC").paginate(page: params[:page], per_page: 1)

	else
		@category_id = Category.find_by(name: params[:category]).id
		@works = Work.where(category_id: @category_id).order("created_at DESC").paginate(page: params[:page], per_page: 1)
	  end
  end

	def new
		@work = current_user.works.build
	end

	def show
		@comments = Comment.where(work_id: @work.id).order("created_at DESC")
		
		if @comments.blank?
			@avg_review = 0
		  else
			@avg_review = @comments.average(:rating)
		  end
	end

	def create
		@work = current_user.works.build(works_params)
		if @work.save
			redirect_to @work
			flash[:success] = "Your Work has been uploaded"
		else
			render 'new'
			flash[:danger] = "Something went wrong, try again"
		end
	end

	def destroy
		@work.destroy
		redirect_to @work
	end

	def update
	    respond_to do |format|
            if @work.update(works_params)
              format.html { redirect_to @work, notice: 'Your work was successfully updated.' }
              
            else
              format.html { render :edit }
            end
          end	
	end

	def search
        @works = Work.all.order("created_at DESC")
        if params[:search]
            @works = Work.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 1)
        else
            @works = Work.all.order("created_at DESC").paginate(page: params[:page], per_page: 1)
        end
    end

	private
        def works_params
            params.require(:work).permit(:name, :category_id, attaches:[])
        end

        def find_work
            @work = Work.find(params[:id])
		end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/comments/_comment.html.erb
<div class="box">
    <article class="media">
        <div class="media-content">
            <div class="content">
                
                <p>
                     <div class="star-rating" data-score= <%= comment.rating %> ></div>
                    <p class = "coment"><%= comment.body%>
                    <small>
                    <p>Posted by name</p>
                    </small>
                </p>
                
            </div>
        </div>
    </article>
</div>


<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/comments/_form.html.erb
<%= bootstrap_form_for ([@work, @work.comments.build]) do |f|%>
 <div class="field">
    <div id="star-rating"></div>
  </div>
    <%= f.text_area :body,label:"Your opinion"%>
 
    <%= f.submit%>
<% end %>


<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'comment[rating]'
  });
</script>

app/views/home/index.html.erb
   
<section>
<div class="banner">
    <div class = "banner-img">
        <%= image_tag  "two.jpg" %>
    </div>

    <div class="banner-title">
        <h1>Werify </h1>
        <h1>Networks</h1>
    </div>
</div>
</section>


<section class = "weri-new">
    <div class="container">
        <div class="weri-box">
            <div class="title-style text-center">
            <h1>New Trends</h1>
            </div>
            <p class="text-center">
            She lives to see the century turn. She lives still.
It’s a Saturday morning in early March, and her grandson Michel collects
her from her flat and walks her through the Jardin des Plantes. Frost glimmers
in the air, and Marie-Laure shuffles along with the ball of her cane out in front
and her thin hair blown to one side and the leafless canopies of the trees
drifting overhead as she imagines schools of Portuguese men-of-war drift,
trailing their long tentacles behind them.
            </p>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Werify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= render 'shared/flash'%> 
    
     <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      <%= link_to "Works", works_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
          <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
           <li><%= link_to "Sign Out",destroy_user_session_path,method: :delete,data:[:confirm,"Are you sure?"]%></li>
         <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>

      <ul class="right-menu text-right ml-auto">
        <li><%= form_tag(search_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search e.g Weriboy...." %></li>
           <li> <%= submit_tag "Search" %></li>
            <% end %>
      </li>
        <li><i class="fa fa-facebook"></i></li> 
        <li><i class="fa fa-instagram"></i></li> 
        <li><i class="fa fa-camera-retro"></i></li> 
        <li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_work_error.html.erb
<% if @work.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@work.errors.count, "error") %>.
    </div>
    <ul>
    <% @work.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/works/_form.html.erb
<%= bootstrap_form_for (@work) do |f| %>
  <%= render 'shared/work_error'%>

  <div class="field">
     <%= f.text_field :name %>
  </div>

   <%= f.label :Select_Category %></p>
    <%=f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a resource"} %>
  </div>

  <div class="field">
     <%= f.file_field :attaches,multiple: true,direct_upload: true %>
  </div>
  
  <div class="btn-group">
    <%= f.submit "Create Work", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/works/_work.html.haml
%h3
    Works

%table.table.table-bordered
    %thead
        %tr
            %td Title
            %td Actions

    %tbody
        - @works.each do |work|
            %tr
                %td #{work.name}
                %td 
                    = link_to work_path(work.id),class:"btn btn-primary" do 
                        Show 
                    

app/views/works/edit.html.erb
<h1>Editing <%= @work.name%></h1>

<%= render 'form', task: @work %>
<div class="btn-group">
    <%= link_to 'Show', @work,class:"btn btn-info" %> 
    <%= link_to 'Back', works_path ,class:"btn btn-info"%>
</div>

app/views/works/index.html.haml
<h2>Index of works</h2>

.container
    .row
        .col-sm-8
            %h3
                Projects

            %table.table.table-bordered
                %thead
                    %tr
                        %td Title
                        
                        %td Actions

                %tbody
                    - @works.each do |work|
                        %tr
                            %td #{work.name}
                            
                            %td 
                                = link_to work_path(work.id),class:"btn btn-primary" do 
                                    Show 

        .col-sm-4
            %h3
                All Categories
            %ul.list-group
                %li= link_to "All Projects", works_path, class: "list-group-item"
                - Category.all.each do |category|
                    %li= link_to  category.name, works_path(category: category.name), class: "list-group-item" 
    



        
    %p
        =link_to "New Tutorial", new_work_path,class:"btn btn-default"
    %p
        =will_paginate @task, renderer: BootstrapPagination::Rails,previous_label:"Newer", next_label: "Older", inner_window: 1, outer_window: 0 

app/views/works/new.html.haml
%h2
    New Projects

= render "form"

app/views/works/search.html.erb
<% if @works.present? %>
    <%= render 'work'%>
<%else%>
    <p>
        There are no projects containing the term(s) <%= params[:search] %>.</p>

</p>

<% end%>

app/views/works/show.html.erb
<h2><%=@work.name %></br>

Average rating
 <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@comments.length} ratings" %></em>

<div class="container">
  <div class="row">
  
    <div class="col-sm-7">


      <p>Available <%= "Attachment".pluralize(@work.attaches.count)%></p>
        <% @work.attaches.each do |attach| %>
          <% if attach.variable? %>
          
            <%= link_to image_tag(attach.variant(resize: "250x250")),attach%>
          <% elsif attach.previewable?%>
            <h3>Video Content</h3>
            <%= link_to image_tag(attach.preview(resize: "250x250")),rails_blob_path(attach, disposition: :attachment)%>
          <% else %>
            <%= link_to attach.filename,rails_blob_path(attach, disposition: :attachment)%>
          <% end %>
          <% end %>

      
        <p>
          <div class="btn-group">
            <%= link_to "Back",works_path, class:"btn btn-default"%>
            <% if current_user = user_signed_in?%>
            <%= link_to "Delete",@work_path,method: :delete,
              data:{confirm:"Are you sure you want to delete #{@work.name}"},
              class:"btn btn-danger" %>
           
            <%= link_to 'Edit', edit_work_path(@work),class:"btn btn-default" %>
            <% end %>
          </div>
        </p>

        </div> 


        <div class="col-sm-5">
<br>
        <section class="section_comments">
          
          <h3>Your thoughts</h3>
          <div class="comment">
            
            <%= render partial: 'comments/comment', collection: @work.comments %>
            <h4>Comment and Rate</h4>
            <div class="reviews">
              
            <%= render partial: 'comments/form' %>
          </div>
        </section>  
        </div>
      <div>
    </div>





<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>